# Generated by Django 3.0.3 on 2020-10-11 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201005_2122'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='post',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='post',
            name='text_html',
        ),
    ]
